const $=s=>document.querySelector(s), $$=s=>document.querySelectorAll(s);
const cats=[...new Set(JOBS.map(j=>j.category))];
const palette=['#dbeafe','#fce7f3','#dcfce7','#ede9fe','#ffedd5','#cffafe','#fef9c3','#e0f2fe'];
let selected=null, compare=[];
const catSel=$('#cat'), aptSel=$('#apt'), q=$('#q'), cards=$('#cards'), detail=$('#detail');
function init(){cats.forEach(c=>{catSel.insertAdjacentHTML('beforeend',`<option>${c}</option>`);$('#chips').insertAdjacentHTML('beforeend',`<button class="chip" data-cat="${c}">${c}</button>`)});$('#count').textContent=JOBS.length;render(); bind(); today();}
function bind(){q.oninput=render; catSel.onchange=render; aptSel.onchange=render; $('#resetBtn').onclick=()=>{q.value='';catSel.value='';aptSel.value='';$$('.chip').forEach(x=>x.classList.remove('on'));render()}; $$('.chip').forEach(ch=>ch.onclick=()=>{let on=ch.classList.toggle('on');$$('.chip').forEach(x=>{if(x!==ch)x.classList.remove('on')});catSel.value=on?ch.dataset.cat:'';render()}); $$('.quick button').forEach(b=>b.onclick=()=>{q.value=b.dataset.quick;render();document.querySelector('#explore').scrollIntoView()}); $('#openMap').onclick=()=>openMap(selected||JOBS[0]); $('#closeMap').onclick=()=>$('#mapModal').classList.remove('show'); $('#expandMap').onclick=()=>$('#floatCard').classList.toggle('max'); $('#darkBtn').onclick=()=>document.body.classList.toggle('dark'); $('#saveBtn').onclick=saveMemo; $('#printBtn').onclick=()=>window.print(); $('#startCinema').onclick=openCinema; $('#closeCinema').onclick=()=>$('#cinemaOverlay').classList.remove('show'); dragFloat();}
function render(){let key=q.value.trim().toLowerCase(), cat=catSel.value, apt=aptSel.value;let list=JOBS.filter(j=>(!cat||j.category===cat)&&(!apt||j.aptitude===apt)&&(!key||[j.name,j.category,j.aptitude,j.description,...j.majors,...j.subjects,...j.keywords].join(' ').toLowerCase().includes(key))); $('#count').textContent=list.length; cards.innerHTML=list.map((j,i)=>card(j,i)).join('')||'<div class="empty-detail"><h3>검색 결과가 없습니다</h3><p>키워드를 줄이거나 전체 분야로 다시 검색해 보세요.</p></div>'; cards.querySelectorAll('.job-card').forEach(el=>{el.onclick=e=>{if(e.target.tagName==='BUTTON')return; showDetail(JOBS[+el.dataset.idx])}}); cards.querySelectorAll('[data-act="detail"]').forEach(b=>b.onclick=()=>showDetail(JOBS[+b.dataset.idx])); cards.querySelectorAll('[data-act="map"]').forEach(b=>b.onclick=()=>openMap(JOBS[+b.dataset.idx]));}
function idxOf(j){return JOBS.indexOf(j)}
function card(j,i){let idx=idxOf(j), g=palette[idx%palette.length];return `<article class="job-card" style="--g:${g}" data-idx="${idx}"><div class="icon">${j.icon}</div><h3>${j.name}</h3><p>${j.description}</p><div class="tags"><span class="tag">${j.category}</span><span class="tag">${j.aptitude}</span><span class="tag">${j.outlook}</span></div><div class="card-actions"><button class="ghost" data-act="detail" data-idx="${idx}">상세</button><button class="primary" data-act="map" data-idx="${idx}">교과맵</button></div></article>`}
function showDetail(j){selected=j;detail.className='';detail.innerHTML=`<div class="detail-hero"><div class="detail-title"><div class="bigicon">${j.icon}</div><div><h2>${j.name}</h2><div>${j.category} · ${j.aptitude}형 · ${j.outlook}</div></div></div><p>${j.description}</p><button class="big-cta" onclick="openMap(selected)">🧩 고교 교과목 연계 지도 열기</button> <button class="big-ghost" onclick="addCompare(selected)">➕ 비교 담기</button></div><div class="detail-grid"><section class="info-card"><h3>🎓 관련 학과</h3><div class="pill-list">${j.majors.map(x=>`<span class="pill">${x}</span>`).join('')}</div></section><section class="info-card"><h3>📚 2022 개정 추천 과목</h3><div class="pill-list">${j.subjects.map(x=>`<span class="pill">${x}</span>`).join('')}</div></section><section class="info-card"><h3>🏛️ 대학 전공에서 배우는 내용</h3>${j.curriculum.map(x=>`<div class="activity">${x}</div>`).join('')}</section><section class="info-card"><h3>💬 상담 질문</h3>${j.questions.map(x=>`<div class="activity">${x}</div>`).join('')}</section><section class="info-card full"><h3>📝 생기부 연계 활동 아이디어 <small>교내·외 대회 제외</small></h3>${j.activities.map(x=>`<div class="activity">${x}</div>`).join('')}</section><section class="info-card full"><h3>👀 입학사정관 시선</h3><p>${j.admission}</p></section></div>`;}
window.openMap=function(j){j=j||selected||JOBS[0]; selected=j; $('#mapModal').classList.add('show'); $('#mapBody').innerHTML=`<div class="map-center"><h2>${j.icon} ${j.name}</h2><p>고교 과목 → 탐구 질문 → 전공 역량으로 이어지는 상담 지도</p></div><div class="subject-map">${j.subjects.map((s,i)=>`<div class="subject-node"><b>${i+1}. ${s}</b><p>${subjectWhy(s,j)}</p><button class="tiny" onclick="toast('${s} 활동 아이디어를 상담 보드에서 확인하세요')">활동 보기</button></div>`).join('')}</div><div class="info-card full" style="margin-top:16px"><h3>연결 전략</h3><p>과목명을 단순 나열하지 말고, 수업 개념을 활용해 문제를 정의하고 자료 조사·분석·발표·피드백으로 이어지게 설계하세요. 대회 실적이 아니라 수업 안에서의 사고 과정과 탐구 태도를 남기는 것이 핵심입니다.</p></div>`;}
function subjectWhy(s,j){if(/수학|통계|미적분|기하/.test(s))return `${j.name}에서 필요한 모델링, 자료 해석, 의사결정의 기초를 만드는 과목입니다.`;if(/물리|역학|전자기/.test(s))return `기술의 원리와 시스템 작동 방식을 설명하는 핵심 과학 과목입니다.`;if(/생명|보건|세포|유전/.test(s))return `생명 현상과 건강 문제를 과학적으로 이해하는 기반이 됩니다.`;if(/사회|경제|법|정치|윤리|지리/.test(s))return `사람과 사회의 맥락 속에서 진로 문제를 해석하게 해 줍니다.`;if(/정보|데이터|인공지능/.test(s))return `데이터 수집, 알고리즘적 사고, 디지털 문제 해결 역량과 직접 연결됩니다.`;return `전공 관심을 구체적인 질문과 표현 활동으로 확장하는 연결 과목입니다.`}
window.addCompare=function(j){if(!compare.find(x=>x.name===j.name)){if(compare.length>=4)compare.shift();compare.push(j)}renderCompare();toast('비교 카드에 담았습니다')}
function renderCompare(){let box=$('#compareBox');box.innerHTML=compare.length?`<h3>⚖️ 전공네컷 비교</h3>${compare.map(j=>`<div class="compare-item"><span>${j.icon} ${j.name}</span><small>${j.subjects.slice(0,2).join(' · ')}</small></div>`).join('')}`:''}
function saveMemo(){localStorage.setItem('major4Memo',JSON.stringify({student:$('#student').value,teacher:$('#teacher').value,grade:$('#grade').value,date:$('#date').value,memo:$('#memo').value,selected:selected?.name}));toast('상담 메모를 저장했습니다')}
function today(){let d=new Date();$('#date').value=`${d.getFullYear()}-${String(d.getMonth()+1).padStart(2,'0')}-${String(d.getDate()).padStart(2,'0')}`;let saved=localStorage.getItem('major4Memo');if(saved){try{let m=JSON.parse(saved);['student','teacher','grade','memo'].forEach(k=>{if(m[k])$('#'+k).value=m[k]})}catch(e){}}}
function openCinema(){let picks=[selected||JOBS[0],...JOBS.filter(j=>j.category===(selected||JOBS[0]).category).slice(0,4)];$('#cinemaStage').innerHTML=`<div class="cinema-stage"><div>NOW SHOWING</div><h2>${picks[0].icon} ${picks[0].name}</h2><p>${picks[0].description}</p><div class="cinema-strip">${picks.map(j=>`<div><h3>${j.icon} ${j.name}</h3><p>${j.subjects.slice(0,3).join(' · ')}</p></div>`).join('')}</div><button class="big-cta" onclick="document.querySelector('#cinemaOverlay').classList.remove('show');showDetail(selected||JOBS[0])">상담 보드로 이동</button></div>`;$('#cinemaOverlay').classList.add('show')}
function toast(t){let el=$('#toast');el.textContent=t;el.classList.add('show');setTimeout(()=>el.classList.remove('show'),1800)}
function dragFloat(){const card=$('#floatCard'), handle=$('#dragHandle');let sx,sy,ox,oy,drag=false;handle.addEventListener('mousedown',e=>{drag=true;sx=e.clientX;sy=e.clientY;let r=card.getBoundingClientRect();ox=r.left;oy=r.top;card.style.transform='none';card.style.left=ox+'px';card.style.top=oy+'px'});window.addEventListener('mousemove',e=>{if(!drag)return;card.style.left=ox+e.clientX-sx+'px';card.style.top=oy+e.clientY-sy+'px'});window.addEventListener('mouseup',()=>drag=false)}
init();
